language: python
python:
  - 2.7
  - 3.4
install: 
  - pip install -r requirements.txt 
  - pip install -r tests/test-requirements.txt
script:
    - nosetests --with-coverage --cover-package=seo_report tests.unit
after_success:
  - coveralls